[profile.default]
src = "src"
out = "out"
libs = []
allow_paths = [
    "node_modules/@openzeppelin/contracts",
    "node_modules/forge-std",
]
remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts",
    "forge-std/=node_modules/forge-std/src",
]

fs_permissions = [{ access = "read", path = "./" }]
